trigger:  none
  # branches:
  #   include:
  #    - '*'

pool:
  # name: SCCR_POC
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- task: HelmDeploy@0
  displayName: 'Add repo of Trino using HELM'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'sccr-azure-sc'
    azureResourceGroup: 'RG-EUS-SCCSPOC-DEV'
    kubernetesCluster: 'AKS-EUS-SCCSPOC-DEV'
    command: 'repo'
    arguments: 'add trino https://trinodb.github.io/charts'

- task: HelmDeploy@0
  displayName: 'Deploy Trino using HELM'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'sccr-azure-sc'
    azureResourceGroup: 'RG-EUS-SCCSPOC-DEV'
    kubernetesCluster: 'AKS-EUS-SCCSPOC-DEV'
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'trino/trino'
    chartVersion: '0.10.2'
    releaseName: 'trino-cluster'
    namespace: 'trino'
    
    # helm install my-trino trino/trino --version 0.10.2
    # helm repo add trino https://trinodb.github.io/charts/