apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.1.0
  # image: acreussccspodevman.azurecr.io/kafka/debezium-connect:1.0.0
  image: gkocur/kafka-connect-debezium-protobuf:1
  replicas: 1
  bootstrapServers: kafka-cluster:9092
  config:
    config.providers: file # set up 'secret' and use comment options in kafka-connect-mysql.yml (database.user, database.password)
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: my-sql-credentials