apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  selector:
    app: zookeeper-cluster
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888
  clusterIP: None    
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: kafka-cluster
  ports:
  - port: 9092
    targetPort: 9092
  type: LoadBalancer